apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi.fullname" . }}
  labels:
    {{- include "fastapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.static.enabled }}
    - port: {{ .Values.static.service.port }}
      targetPort: static
      protocol: TCP
      name: static
    {{- end }}
  selector:
    {{- include "fastapi.selectorLabels" . | nindent 4 }}
